config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'rooms#home'
  get 'rooms/post'
  post 'reservations/new'

  resources :rooms do
    collection do
      get 'search'
    end
  end
  resources :users
  resources :reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations, dependent: :destroy
    mount_uploader :image, ImageUploader

    validates :name, presence: true
    validates :introduction, presence: true
    validates :fee, presence: true
    validates :address, presence: true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :search
 
  def index
    @search = Room.ransack(params[:q])
    @rooms = @search.result
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :introduction, :fee, :address, :image, :user_id))
    if @room.save
      flash[:notice] = "ルームを登録しました。"
      redirect_to root_path
    else
      flash[:alert] = "ルームを登録できませんでした。"
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
  end

  def destroy
    @room = Room.find_by(params[:id])
    @room.destroy
    redirect_to root_path
  end

  def search
    @q = Room.ransack(params[:q])
  end

  def home
    @rooms = Room.all
  end

  def post
    @rooms = Room.all
  end
end

app/views/rooms/home.html.erb
<% if flash[:notice] %>
<p class = "notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
<p class = "alert"><%= flash[:alert] %></p>
<% end %>

<div class="background">
  <div class="home-contents search">
    <h1 class="home-title">PotepanShareでまだ体験したことのない旅をしよう</h1>
    <%= search_form_for @search do |f| %>
      <%= f.text_field :address_cont , placeholder: "エリア" , style: "width:100%; padding:5px; margin:5px;" %>
      <%= f.submit "探す" , class: "btn btn-primary", style: "width:100%; padding:5px; margin:5px;" %>
    <% end %>
  </div>
  <div class="home-contents reccomend">
  <h2 class="hometitle">おすすめのエリア</h2>
    <a class="location" href="http://localhost:3000/rooms?q%5Baddress_cont%5D=%E6%9D%B1%E4%BA%AC&commit=%E6%A4%9C%E7%B4%A2">東京</a>
    <a class="location" href="http://localhost:3000/rooms?q%5Baddress_cont%5D=%E5%A4%A7%E9%98%AA&commit=%E6%A4%9C%E7%B4%A2">大阪</a>
    <a class="location" href="http://localhost:3000/rooms?q%5Baddress_cont%5D=%E4%BA%AC%E9%83%BD&commit=%E6%A4%9C%E7%B4%A2">京都</a>
    <a class="location" href="http://localhost:3000/rooms?q%5Baddress_cont%5D=%E6%9C%AD%E5%B9%8C&commit=%E6%A4%9C%E7%B4%A2">札幌</a>
  </div>
</div>

app/views/rooms/index.html.erb
<h1 class="title">ルーム一覧</h1>

<table class="general-box">
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>投稿日時</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
    <tr>
      <% if room.image.present? %>
      <td><%= image_tag room.image.url(:thumb) %></td>
      <% else %>
      <td>No Image</td>
      <% end %>
      <td><%= link_to room.name, room %></td>
      <td class="td-limit"><%= room.introduction %></td>
      <td><%= room.fee %>円/日</td>
      <td><%= room.created_at.to_s(:datetime_jp) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "ホーム画面に戻る", root_path, style: "margin:3%" %>

app/views/rooms/new.html.erb
<% if flash[:notice] %>
<p class = "notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
<p class = "alert"><%= flash[:alert] %></p>
<% end %>

<h1 class="title">新規ルーム登録</h1>

<!--登録フォーム--!>
<%= form_with model: @room do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
  <table class="general-box">
    <tr>
      <th><span class="required">必須</span><%= f.label :name , "ルーム名" %></th>
      <td><%= f.text_field :name, style: "width:100%" %></td>
    </tr>
  
    <tr>
      <th><span class="required">必須</span><%= f.label :introduction , "ルーム紹介" %></th>
      <td><%= f.text_area :introduction, style: "height: 200px; width:100%" %></td>
    </tr>
  
    <tr>
      <th><span class="required">必須</span><%= f.label :fee , "料金" %></th>
      <td><%= f.number_field :fee, style: "width:100%" %></td>
    </tr>
  
    <tr>
      <th><span class="required">必須</span><%= f.label :address , "住所" %></th>
      <td><%= f.text_field :address, style: "width:100%" %></td>
    </tr>
  
    <tr>
      <th><%= f.label :image , "ルーム画像" %></th>
      <td><%= f.file_field :image, style: "width:100%" %></td>
    </tr>
  </table>
  
  <%= f.submit "登録", class: "btn btn-primary roombtn" %>
<% end %>

app/views/rooms/post.html.erb
<h1 class="title">登録済みルーム一覧</h1>

<table class="general-box">
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>登録日時</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
    <% if room.user_id == current_user.id %>
    <tr>
      <% if room.image.present? %>
      <td class="td-limit"><%= image_tag room.image.url(:thumb) %></td>
      <% else %>
      <td>No Image</td>
      <% end %>
      <td><%= link_to room.name, room %></td>
      <td class="td-limit"><%= room.introduction %></td>
      <td><%= room.fee %></td>
      <td><%= room.created_at.to_s(:datetime_jp) %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "ホーム画面に戻る", root_path, style: "margin:3%" %>

app/views/rooms/show.html.erb
<% if flash[:notice] %>
<p class = "notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
<p class = "alert"><%= flash[:alert] %></p>
<% end %>

<h1 class="title">ルーム詳細</h1>

<% if @room.image.present? %>
<div class="room-image"><%= image_tag @room.image.url(:content) %></div>
<% else %>
<div class="image-alt">No Image</div>
<% end %>

<!--予約フォーム--!>
<div class="rsv-box">
  <%= form_with url: new_reservation_path do |f| %>
  <%= f.hidden_field :room_id, value: @room.id %>

  <div class="rsv-content">
    <%= @room.fee %>円 / 日
  </div>

  <div class="rsv-content">
    <%= f.label :start_date , "開始日" %><br />
    <%= f.date_field :start_date, style: "width:80%" %>
  </div>

  <div class="rsv-content">
  <%= f.label :end_date , "終了日" %><br />
  <%= f.date_field :end_date, style: "width:80%" %>
  </div>

  <div class="rsv-content">
  <%= f.label :how_many_people , "人数" %><br />
  <%= f.number_field :how_many_people, style: "width:20%" %>
  </div>
  <% if user_signed_in? %>
  <%= f.submit "予約する", class: "btn btn-primary rsv-btn" %>
  <% else %>
  <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary rsv-btn" %>
  <% end %>
  </div>
<% end %>

<table class="general-box">
  <thead>
    <tr>
      <th>ルーム名</th>
      <th>住所</th>
      <th>ルーム紹介文</th>
      <th>登録ユーザー名</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @room.name %></td>
      <td><%= @room.address %></td>
      <td class="td-limit"><%= @room.introduction %></td>
      <td><%= @room.user.name %></td>
    </tr>
  </tbody>
</table>

<%= link_to "ホーム画面に戻る", root_path, style: "margin:3%" %>